### PR TITLE
poggers

### PR DESCRIPTION
**Pull request by Miguel-cyber**

### CODE REVIEW

**Comment by quinchs** [comment]
I'm deprecating that command as It serves no use anymore

**Comment by tnlyr** [comment]
Yes!1

**Comment by Miguel-cyber** [comment]
grammar is important!

**Comment by tnlyr** [comment]
Quin you have to improve your grammar!1

**Comment by quinchs** [comment]
Yes tonelyr, there comes a time in your life where you need to grow a pair and take 2 extra seconds to thing about what you are typing. And improve on it where seem fit

**Pull request closed without merging**
